# Generated by Django 5.0.6 on 2024-06-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='Album_release_date',
        ),
        migrations.RemoveField(
            model_name='album',
            name='musician',
        ),
    ]
