# Generated by Django 5.0.6 on 2024-06-20 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_remove_album_album_release_date_and_more'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Album_release_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musician.musician'),
        ),
        migrations.AlterField(
            model_name='album',
            name='AlbumName',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
