# Generated by Django 5.0.6 on 2024-06-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_album_album_release_date_album_musician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Rating',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='Album_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
