# Generated by Django 5.0.6 on 2024-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_album_rating_alter_album_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20, null=True),
        ),
    ]
