# Generated by Django 5.0.6 on 2024-06-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_alter_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Album_release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
