# Generated by Django 5.0.6 on 2024-06-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_alter_album_album_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Album_release_date',
            new_name='album_release_date',
        ),
        migrations.RemoveField(
            model_name='album',
            name='musician',
        ),
    ]
