# Generated by Django 5.0.6 on 2024-06-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_rename_album_release_date_album_album_release_date_and_more'),
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.album'),
        ),
    ]
